include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
    - lib/**/*.g.*.dart
    - lib/**/*.gr.dart
    - lib/**/*.graphql.dart
    - lib/presentation/l10n/messages*.dart
    - test/**/*.mocks.dart
  errors:
    missing_required_param: error
    missing_return: error
    # allow having TODOs in the code
    todo: ignore

linter:
  rules:
    # Disable
    avoid_function_literals_in_foreach_calls: false

    # Enable
    always_declare_return_types: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_double_and_int_checks: true
    avoid_catching_errors: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_js_rounded_ints: true
    avoid_private_typedef_functions: true
    avoid_returning_null: true
    avoid_returning_null_for_future: true
    avoid_returning_this: true
    avoid_slow_async_io: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    cascade_invocations: true
    diagnostic_describe_all_properties: true
    directives_ordering: true
    flutter_style_todos: true
    invariant_booleans: true
    join_return_with_assignment: true
    literal_only_boolean_expressions: true
    one_member_abstracts: true
    only_throw_errors: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
    test_types_in_equals: true
    throw_in_finally: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_null_aware_assignments: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unsafe_html: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
