name: rxdart_buffered_subject
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/tjarvstrand/rxdart_buffered_subject

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0

